name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: geowatson/flutter-latest@1.0.1
        with:
          ref: ${{ github.head_ref}}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: ./
      - run: |
          git config --global user.email jkaae93@gmail.com
          git config --global user.name Serim
          git remote add origin https://jkaae93:jl8085++@github.com/jkaae93/anno1800-calculator.git
          rm -rf ./docs
          mkdir ./docs
          cp ./build/web ./docs
          git status
          git checkout -b master
          git add .
          git commit -m "update"
          git push origin master
